---
title: "Using RMarkdown to report data of a lot of chronic pain patients"
author: "your name"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Background

There are many online references available for R Markdown. One of the books that can be bought but is also freely available on the web is the R Markdown Cookbook by Yihui Xie et al. You can find it here: https://bookdown.org/yihui/rmarkdown-cookbook/ The markdown language ignores 'enter'. To start a new line, hit space twice (that's what I did just after the link to the book). Plain text could be placed here to introduce the report that you're making. For this tutorial, we will focus on the results section, as this shows best the integration between R code and text. Text can easily be made bold, italic, or, when you explicitly want to refer to R code but without actually invoking R you can use mean(). If you'd like to throw some maths into the mix, you can write simple expressions inline, or where they are easier to read. As you can see, this is just an easy formula, but expand as you like!

Results

The data are read from a comma seperated values file (.csv file) created from an SPSS-file that contains the raw data. The data are a subset of a large cohort from the Maastricht UMC+. These data will be used to perform some simple statistical analyses, the results of which will be integrated in this report. First, let's make an excerpt of the data visible in the report. For instance, let's present the first 5 rows of data.

This may be useful in a report, but it would require knowledge of column names and hence, some sort of a codebook. A better option would be to summarize the dataset using descriptive statistics.

Descriptive statistics

For the actual results of analyses, naturally we would start with descriptive statistics. The cohort consisted of 742 chronic pain patients.  Of all patients, 326 (43.9%) were male, with an average age (standard deviation) of 57.18 (15.14). In case we had many more characteristics, a baseline table would be a better option.

We could have reported on the actual number of patients in the title, as a teaser for the intended reader. To do so, we can specify part of the YAML metadata here. this makes sure that in case the dataset is updated (or we apply different eligibility criteria), the title is automatically updated as well.

Say we were most interested in a simple association between complaints of anxiety and depression in these patients. We could compute the correlation by simply typing r code here, with its associated p-value of p=0.001. However, this is just a measure of the strength of the linear relation between these two variables. this may obscure a more interesting association.

To get a better impression of the association between two continuous variables, a figure in the report would benefit the reader.

Regression model

Using RMarkdown, you can easily print how regression models were built. Say we would be interested to see whether there is an association between a number of baseline characteristics (e.g., sex, age, having a partner, and having one or more children) and depressive complaints. Before showing the actual results in a table, providing the regression model structure can be a lot of insight:

As you can see, this is only the theoretical model, containing the structure, but no estimated regression coefficients yet. We can do this as follows:

Note that the residual term in the model formula is now omitted, and the outcome variable now has a roof over its head, denoting that this is the estimated HADS depression score that can be calculated according to the formula. However, this is not the usual way to present results from a regression model (we have no confidence intervals, for instance). For that, we could report results neatly in a table. Table 1 shows regression coefficients of the linear model.

That concludes the tutorial on how to work with R Markdown! For your group assignment, make sure to integrate R into your R Markdown file, so that everyhing that depends on the dataset is automatically updated in case something changes to the data.

References
